### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [shinotanaka/prj-rev-bwfs-dasmoto#4]
Excellent over this was a good job.   The mistakes I mentioned happen more often due to a lack of experience than anything else.  

I would organize your html into divs for each section.  Then figure out how to reduce the repetition in your css and remove the unneeded code.

After that take a look at bootstrap, http://getbootstrap.com/ .  Think about or even try to add this into your website and experiment with it to make it mobile friendly.

**Comment by shinotanaka** [comment]
Hi Farish,

Thanks so much for the great feedback and bootstrap reco. All duly noted!


Best,
Shino
